import { createFileRoute, useNavigate, Link, useSearch } from '@tanstack/react-router'
import { useAuthContext } from '@/contexts/AuthContext'
import { QuizSessionManager } from '@/components/assessment/QuizSessionManager'
import { useEffect } from 'react'
import { ArrowLeft, Brain } from 'lucide-react'
import { z } from 'zod'

const searchSchema = z.object({
  lessonId: z.number().optional(),
})

export const Route = createFileRoute('/quiz/$topic')({
  component: RouteComponent,
  validateSearch: searchSchema,
})

// Fallback map used only when no lessonId is in the URL (e.g. direct navigation)
const topicToNextLesson: Record<string, number> = {
  'boolean-algebra': 2,
  'logic-gates': 3,
  'truth-tables': 4,
  'number-systems': 8,
  'binary-arithmetic': 9,
  'complements': 10,
  'karnaugh-maps': 5,
}

function RouteComponent() {
  const { topic } = Route.useParams()
  const { lessonId } = useSearch({ from: '/quiz/$topic' })
  const navigate = useNavigate()
  const { user } = useAuthContext()

  useEffect(() => {
    if (!user) {
      navigate({ to: '/login' })
    }
  }, [user, navigate])

  if (!user) return null

  // If we came from a lesson page, go to the very next lesson (lessonId + 1).
  // Otherwise fall back to the topic→next-lesson map for direct URL navigation.
  const nextLessonId = lessonId ? lessonId + 1 : topicToNextLesson[topic]

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-4 pt-24 pb-16">
        {/* Header */}
        <div className="mb-6">
          <Link to="/roadmap" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="w-4 h-4" />
            Back to Dashboard
          </Link>
        </div>

        {/* Quiz */}
        <QuizSessionManager
          userId={user.id}
          topic={topic}
          lessonId={lessonId}
          nextLessonId={nextLessonId}
          onComplete={() => {
            // Could add redirect logic here if needed
          }}
        />

        {/* Info box */}
        <div className="mt-8 p-4 rounded-xl border border-purple-200 bg-purple-50/50 dark:border-purple-900 dark:bg-purple-900/10 text-sm text-purple-800 dark:text-purple-200">
          <p className="font-semibold mb-1 flex items-center gap-2">
            <Brain className="w-4 h-4" />
            About Adaptive Assessments
          </p>
          <p>Questions are dynamically generated by AI based on your Exponential Moving Average (EMA) mastery score. The more you practice, the more challenging the questions become.</p>
        </div>
      </div>
    </div>
  )
}

