import { createFileRoute, useNavigate, Link, useSearch, redirect } from '@tanstack/react-router'
import { supabase } from '@/utils/supabase'
import { useAuthContext } from '@/contexts/AuthContext'
import { QuizSessionManager } from '@/components/assessment/QuizSessionManager'
import { useEffect } from 'react'
import { ArrowLeft, Brain } from 'lucide-react'
import { z } from 'zod'

const searchSchema = z.object({
  lessonId: z.number().optional(),
})

export const Route = createFileRoute('/quiz/$topic')({
  beforeLoad: async () => {
    const { data: { session } } = await supabase.auth.getSession()
    if (!session) {
      throw redirect({
        to: '/login',
      })
    }
  },
  component: RouteComponent,
  validateSearch: searchSchema,
})

// Fallback map used only when no lessonId is in the URL (e.g. direct navigation)
// Values are database IDs for the next lesson in display order
const topicToNextLesson: Record<string, number> = {
  'number-systems': 4,       // After number systems → Binary Arithmetic (lesson 4)
  'binary-arithmetic': 5,    // After binary arithmetic → Complements (lesson 5)
  'complements': 6,          // After complements → Signed/Unsigned (lesson 6)
  'boolean-algebra': 9,      // After boolean algebra → Logic Gates (lesson 9)
  'logic-gates': 10,         // After logic gates → Truth Tables (lesson 10)
  'truth-tables': 11,        // After truth tables → Simplification (lesson 11)
  'karnaugh-maps': 8,        // After karnaugh maps → Intro to Boolean Algebra (lesson 8)
}

function RouteComponent() {
  const { topic } = Route.useParams()
  const { lessonId } = useSearch({ from: '/quiz/$topic' })
  const navigate = useNavigate()
  const { user } = useAuthContext()

  useEffect(() => {
    if (!user) {
      navigate({ to: '/login' })
    }
  }, [user, navigate])

  if (!user) return null

  // IDs are now sequential (1-11), so lessonId + 1 works for next lesson.
  // Cap at 11 (last lesson). Fall back to the topic→next-lesson map for direct URL navigation.
  const nextLessonId = lessonId
    ? (lessonId < 11 ? lessonId + 1 : undefined)
    : topicToNextLesson[topic]

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-4 pt-24 pb-16">
        {/* Header */}
        <div className="mb-6">
          <Link to="/roadmap" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="w-4 h-4" />
            Back to Dashboard
          </Link>
        </div>

        {/* Quiz */}
        <QuizSessionManager
          userId={user.id}
          topic={topic}
          lessonId={lessonId}
          nextLessonId={nextLessonId}
          onComplete={() => {
            // Could add redirect logic here if needed
          }}
        />

        {/* Info box */}
        <div className="mt-8 p-4 rounded-xl border border-purple-200 bg-purple-50/50 dark:border-purple-900 dark:bg-purple-900/10 text-sm text-purple-800 dark:text-purple-200">
          <p className="font-semibold mb-1 flex items-center gap-2">
            <Brain className="w-4 h-4" />
            About Adaptive Assessments
          </p>
          <p>Questions are dynamically generated by AI based on your Exponential Moving Average (EMA) mastery score. The more you practice, the more challenging the questions become.</p>
        </div>
      </div>
    </div>
  )
}

